version: '3'
services:
  truffle_refund:
    image: harttruffle:dev
    environment:
    - DEVELOPMENT_HOST=${DEVELOPMENT_HOST}
    - LIVE_HOST=${LIVE_HOST}
    - LIVE_ADDRESS=${LIVE_ADDRESS}
    - LIVE_PORT=${LIVE_PORT} 
    command: bash -c "truffle compile --network development"
    volumes:
    - .:/code